name: learn-github-actions # Opcional - Como o nome do fluxo de trabalho irá aparecer na aba Ações do repositório de GitHub
on: [push] # Especifica o gatilho para este fluxo de trabalho. 
jobs: # Agrupa todos os trabalhos executados no fluxo
  check-bats-version: # Define uma tarefa
    runs-on: ubuntu-latest # Configura onde o worker vai ser executado
    steps: # Agrupa quais passos serão executados
      - uses: actions/checkout@v3 # A palavra-chave use especifica que esta etapa irá executar v3 da ação actions/checkout. Esta é uma ação que faz o check-out do seu repositório para o executor, permitindo que você execute scripts ou outras ações com base no seu código (como ferramentas de compilação e teste). Você deve usar a ação de checkout sempre que o fluxo de trabalho for executado no código do repositório.
      - uses: actions/setup-java@v3 # Essa etapa usa a ação de actions/setup-node@v3 para instalar a versão especificada do Java
        with:
          java-version: '11'
          distribution: 'temurin'
      - run: java -version # A palavra chave RUn diz ao job para executar um comando
